In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.16.1


Using TensorFlow backend.


Use the Maths function in tensorflow

In [5]:
#abs function which work as Absolute value change the negative value to positive

a = tf.constant([-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0], dtype=tf.float32)
print(a)
print(tf.abs(a))
print(np.abs(a.numpy()))

tf.Tensor([-3. -2. -1.  0.  1.  2.  3.], shape=(7,), dtype=float32)
tf.Tensor([3. 2. 1. 0. 1. 2. 3.], shape=(7,), dtype=float32)
[3. 2. 1. 0. 1. 2. 3.]


Complex Number

In [11]:
#abs function which work as Absolute value change the negative value to positive
Complux_number = tf.constant([-2.25+4.75j])
print(Complux_number)
print(tf.abs(Complux_number))
print(np.abs(Complux_number.numpy()))

tf.Tensor([-2.25+4.75j], shape=(1,), dtype=complex128)
tf.Tensor([5.25594901], shape=(1,), dtype=float64)
[5.25594901]


Squre of Numbers

In [19]:
square_of_numbers = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(tf.square(square_of_numbers))
print(np.square(square_of_numbers.numpy()))
#take the square of the 2 numbers and add them using tensorflow and numpy
sqroot = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("This is the square of the 2 numbers using tensorflow ",tf.square(sqroot))

print("This is the square of the 2 numbers using numpy ",np.sqrt((3**2)+4**2))


tf.Tensor([  1   4   9  16  25  36  49  64  81 100], shape=(10,), dtype=int32)
[  1   4   9  16  25  36  49  64  81 100]
This is the square of the 2 numbers using tensorflow  tf.Tensor([  1   4   9  16  25  36  49  64  81 100], shape=(10,), dtype=int32)
This is the square of the 2 numbers using numpy  5.0


Add the two tensor

In [20]:
a=tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b=tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(tf.add(a,b))
print(np.add(a.numpy(),b.numpy()))


tf.Tensor([ 2  4  6  8 10 12 14 16 18 20], shape=(10,), dtype=int32)
[ 2  4  6  8 10 12 14 16 18 20]


Subtraction 

In [32]:
s=tf.constant([2, 4, 6, 8, 5])
t=tf.constant([1, 2, 3, 4, 5])
#g=tf.constant([1, 1, 1, 1, 4])
print(tf.subtract(s,t))
print(np.subtract(s.numpy(),t.numpy()))

tf.Tensor([1 2 3 4 0], shape=(5,), dtype=int32)
[1 2 3 4 0]


Broadcosting 

In [36]:
s=tf.constant([2, 4, 6, 8, 5])
t=tf.constant([ 2])
#g=tf.constant([1, 1, 1, 1, 4])
print(tf.subtract(s,t))
print(np.subtract(s.numpy(),t.numpy()))

tf.Tensor([0 2 4 6 3], shape=(5,), dtype=int32)
[0 2 4 6 3]
