Multiplication 


In [14]:
import tensorflow as tf 
matrix_1=tf.constant([[1,2,3],
                      [3,3,4],
                      [3,3,4]])
matrix_2=tf.constant([[3,2,4],
                      [3,3,4],
                      [3,3,4]])
print(tf.shape(matrix_1))
print(tf.shape(matrix_2))
print(tf.linalg.matmul(
    matrix_1,
    matrix_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
))

tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(
[[18 17 24]
 [30 27 40]
 [30 27 40]], shape=(3, 3), dtype=int32)


Take a traspose of a Matrix Transpose change the matrix row to colum

In [15]:
print(tf.transpose(matrix_1))

tf.Tensor(
[[1 3 3]
 [2 3 3]
 [3 4 4]], shape=(3, 3), dtype=int32)


In [16]:
print(matrix_1@matrix_2)

tf.Tensor(
[[18 17 24]
 [30 27 40]
 [30 27 40]], shape=(3, 3), dtype=int32)


In [19]:
print(matrix_1,tf.linalg.adjoint(matrix_1))

tf.Tensor(
[[1 2 3]
 [3 3 4]
 [3 3 4]], shape=(3, 3), dtype=int32) tf.Tensor(
[[1 3 3]
 [2 3 3]
 [3 4 4]], shape=(3, 3), dtype=int32)
