Multiplication 


In [1]:
import tensorflow as tf 
matrix_1=tf.constant([[1,2,3],
                      [3,3,4],
                      [3,3,4]])
matrix_2=tf.constant([[3,2,4],
                      [3,3,4],
                      [3,3,4]])
print(tf.shape(matrix_1))
print(tf.shape(matrix_2))
print(tf.linalg.matmul(
    matrix_1,
    matrix_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
))


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Muhammad Ihtesham\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

Take a traspose of a Matrix Transpose change the matrix row to colum

In [ ]:
print(tf.transpose(matrix_1))

tf.Tensor(
[[1 3 3]
 [2 3 3]
 [3 4 4]], shape=(3, 3), dtype=int32)


In [ ]:
print(matrix_1@matrix_2)

tf.Tensor(
[[18 17 24]
 [30 27 40]
 [30 27 40]], shape=(3, 3), dtype=int32)


In [ ]:
print(matrix_1,tf.linalg.adjoint(matrix_1))

tf.Tensor(
[[1 2 3]
 [3 3 4]
 [3 3 4]], shape=(3, 3), dtype=int32) tf.Tensor(
[[1 3 3]
 [2 3 3]
 [3 4 4]], shape=(3, 3), dtype=int32)
