In [12]:
import numpy as np 
A=np.array([[2,3,1],
            [5,3,2]])
B=np.array([[5,3,2],
            [5,2,2]])
#multiply the A and B matrix
print(np.multiply(A,B),"\n")
# #Mutiplication using einsum function
print(np.einsum("ij,kl -> ik",A,B))

[[10  9  2]
 [25  6  4]] 

[[ 60  54]
 [100  90]]


Transpose using Einsum


In [18]:
A=np.array([[2,3,1],
            [5,3,2]])
print("This will give the transpose of the matrix",np.einsum("ij -> ji",A)) 
#the sum of the array 
print("This will give the Sum of Full Matrix",np.einsum('ij ->',A))
#the sum of the Colum
print("This will give the Sum of Colum in the  Matrix",np.einsum('ij -> j',A))
#the sum of the row
print("This will give the Sum of Rows in the  Matrix",np.einsum('ij -> i',A))

This will give the transpose of the matrix [[2 5]
 [3 3]
 [1 2]]
This will give the Sum of Full Matrix 16
This will give the Sum of Colum in the  Matrix [7 6 3]
This will give the Sum of Rows in the  Matrix [ 6 10]
