In [2]:
import tensorflow as tf



print(tf.__version__)

In [5]:
print(tf.__version__)

2.16.1


Creating Tensor with tf.constent

In [8]:
Scalar = tf.constant(42)
Scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Check the number of Dimentions of a Tensor

In [13]:
Scalar.ndim

0

Create a vector 

In [14]:
vector=tf.constant([12,12,34])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 12, 34])>

Check the dimention of the vector

In [15]:
vector.ndim

1

Create a matrix 

In [16]:
matrix=tf.constant([[12,34],[56,78]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 34],
       [56, 78]])>

matrix Dimention

In [17]:
matrix.ndim

2

Create the Float Matrix

In [19]:
float_Matrix=tf.constant([[12.2,34.3],[56.3,78.3]])
float_Matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.2, 34.3],
       [56.3, 78.3]], dtype=float32)>

Tensor Creating

In [20]:
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[1,2,3],[4,5,6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])>

Check the tensor Dimention


In [24]:
tensor.ndim

3