This is the code of Integer values in tensorflow

In [9]:
import tensorflow as tf

int_tensor=tf.constant([[2,3,4,5,6,],
                       [2,3,4,5,6,]])
print(int_tensor)
print(int_tensor.ndim)

tf.Tensor(
[[2 3 4 5 6]
 [2 3 4 5 6]], shape=(2, 5), dtype=int32)
2


Boolen in tensorflow 

In [12]:
bool_tensor=tf.constant([[True,True,False],
                         [True,True,True]])
print(bool_tensor)
bool_tensor.ndim

tf.Tensor(
[[ True  True False]
 [ True  True  True]], shape=(2, 3), dtype=bool)


2

String in tensor flow

In [13]:
string_tensor=tf.constant(["Ihtesham","Khan","Roshan"])
print(string_tensor)

tf.Tensor([b'Ihtesham' b'Khan' b'Roshan'], shape=(3,), dtype=string)
