In [6]:
import tensorflow as tf 

Identity_Matrix=tf.eye(4,4,None,tf.dtypes.int16,None)
print(Identity_Matrix)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int16)


Using Boolen 

In [7]:
Identity_Matrix=tf.eye(4,4,None,tf.dtypes.bool,None)
print(Identity_Matrix)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]], shape=(4, 4), dtype=bool)


Using Float

In [8]:
Identity_Matrix=tf.eye(4,4,None,tf.dtypes.float16,None)
print(Identity_Matrix)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float16)


Fill Tensor Making Using The Fuction fill

In [12]:
Fill_tensor=tf.fill(
    dims=[1,3,3], value=4, name=None, layout=None
)
print(Fill_tensor)

tf.Tensor(
[[[4 4 4]
  [4 4 4]
  [4 4 4]]], shape=(1, 3, 3), dtype=int32)
