Make a Matrix with all 1 elements on it

In [3]:
import tensorflow as tf
one_tf=tf.ones(
    shape=[2, 3],
    dtype=tf.dtypes.int8,
    name=None,
    layout=None
)
print(one_tf)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int8)


Convert all the Matrix in 1 

In [4]:
make_a_matrix=tf.Variable([[2,4,3,5],
                          [2,4,3,5]],dtype=tf.int8)
print(make_a_matrix)
 
#know convert all the elements of this matrix in to 1
convert_matrix_in_one=tf.ones_like(make_a_matrix)
print(convert_matrix_in_one)


<tf.Variable 'Variable:0' shape=(2, 4) dtype=int8, numpy=
array([[2, 4, 3, 5],
       [2, 4, 3, 5]], dtype=int8)>
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]], shape=(2, 4), dtype=int8)
