Make a Matrix of Zero

In [4]:
import tensorflow as tf 
zero_matrix=tf.zeros([3,3],dtype=tf.int16)
zero_matrix

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)>

Convert the Matrix into zero

In [8]:
matrix=tf.Variable([3,4,5,6])
convert_the_matrix_in_zero=tf.zeros_like(
    matrix
)
print(convert_the_matrix_in_zero)

tf.Tensor([0 0 0 0], shape=(4,), dtype=int32)
