In [15]:
import tensorflow as tf 
create_a_random_tensor=tf.random.normal([3,3],5,20,dtype=tf.dtypes.float32)
print(create_a_random_tensor)

tf.Tensor(
[[ -5.1574907  10.195328   -4.8788757]
 [  3.141136  -24.56399    36.183037 ]
 [ -5.5786896 -17.927694   -6.0669575]], shape=(3, 3), dtype=float32)


In [20]:
create_a_random_tensor_by_uniform=tf.random.uniform([10,10],minval=0,maxval=1000,dtype=tf.dtypes.int32)
print(create_a_random_tensor_by_uniform)


tf.Tensor(
[[799  48  45 923 339 975 236 419 353 159]
 [409 220 882 508 541  79 334 681 346 199]
 [674  57 336 415 616 163 417 504 114 820]
 [406 668 859 206 360 122  96 755 558 101]
 [345  57  26 214 280 665 769 431 293 436]
 [507 820 208 729 279 557 107 635 728 271]
 [735 116  75 426 157 636 497  52 359 645]
 [147 499 773 645 369 499 425 416 554 699]
 [598 995 357 276 689 109 881 830 728 204]
 [248   7 453 340 944 432 650 328 714 187]], shape=(10, 10), dtype=int32)


Using the Seed

In [21]:
create_a_random_tensor_by_uniform_use_seed=tf.random.uniform([4,4],minval=0,maxval=10,dtype=tf.dtypes.int32,seed=10)
print(create_a_random_tensor_by_uniform_use_seed)
 

tf.Tensor(
[[0 2 5 7]
 [2 2 3 5]
 [9 0 2 3]
 [0 1 4 1]], shape=(4, 4), dtype=int32)
